// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cotbkbwmffmedoclzbam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvdGJrYndtZmZtZWRvY2x6YmFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxNzY5ODMsImV4cCI6MjA1NTc1Mjk4M30.q-fJgpbPHbBGB1BY6rpzloujiqLExCIV5nQCR_8jdFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);